sudo: required

services:
  - docker

after_success:
- if ([ "$TRAVIS_BRANCH" == "rm-census" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]) || ([ "$TRAVIS_BRANCH" == "automate-census-docker-build" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]); then
  docker build -t "${DOCKER_GCP_LOCATION}"/census-rm-sample .;
  docker login -u "${DOCKER_GCP_USERNAME}" -p "${DOCKER_GCP_PASSWORD}" "${DOCKER_GCP_REGISTRY}";
  docker push "${DOCKER_GCP_LOCATION}"/census-rm-sample;
  fi

branches:
  only:
    - rm-census
    - automate-census-docker-build
